---
- hosts: cisco1
  connection: local
  gather_facts: false

  tasks:
   - name: my first telnet task
      telnet:
        username: ciscosshconnect
        password: 908oiejgioehjgoi34u4tg043hjgioh5j34kjr4e3h35e345hj45iuio435g
        login_prompt: "Username: "
        password_prompt: "assword:"
        ports: 23
        prompts: ["#"]
        command:
          - sh vers
        register: output
   - debug: var=output
